# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "org.cloudfoundry.openjdk"
name = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.0-M9"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata.default-versions]
openjdk-jdk = "11.*"
openjdk-jre = "11.*"

[[metadata.dependencies]]
id      = "openjdk-jre"
name    = "OpenJDK JRE"
version = "8.0.212"
uri     = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jre_x64_linux_hotspot_8u212b04.tar.gz"
sha256  = "96d24d94c022b3e414b612cae8829244329d71ad2cce790f099c020f33247e7e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "openjdk-jre"
name    = "OpenJDK JRE"
version = "11.0.3"
uri     = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jre_x64_linux_hotspot_11.0.3_7.tar.gz"
sha256  = "d2df8bc799b09c8375f79bf646747afac3d933bb1f65de71d6c78e7466ff8fe4"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "openjdk-jre"
name    = "OpenJDK JRE"
version = "12.0.1"
uri     = "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12/OpenJDK12U-jre_x64_linux_hotspot_12.0.1_12.tar.gz"
sha256  = "85b3c4065b1540f1d0dbe533955a199e54a0cbe7bd6e1111e59d54e68b2f5b43"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "openjdk-jdk"
name    = "OpenJDK JDK"
version = "8.0.212"
uri     = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jdk_x64_linux_hotspot_8u212b04.tar.gz"
sha256  = "09f6ccbfd8a86e52665b56751403fd4e2513ad071e2b3f36bab73f86273d1ead"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "openjdk-jdk"
name    = "OpenJDK JDK"
version = "11.0.3"
uri     = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz"
sha256  = "23cded2b43261016f0f246c85c8948d4a9b7f2d44988f75dad69723a7a526094"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "openjdk-jdk"
name    = "OpenJDK JDK"
version = "12.0.1"
uri     = "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12/OpenJDK12U-jdk_x64_linux_hotspot_12.0.1_12.tar.gz"
sha256  = "dd3fdf3771a05a010029c1cf1aef516928eab55d6f5eb019008875e9ccbc8337"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[metadata]
pre_package = "ci/build.sh"
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "buildpack.toml",
]
